# RHOA HOUSEWIVES
nene = Housewife.find_or_create_by(firstname:"NeNe", lastname:"Leakes", current: true, image:"https://i.pinimg.com/originals/1e/f9/ac/1ef9acae1f3f3bea903b14807d9352ae.png")
sheree = Housewife.find_or_create_by(firstname:"Shereé", lastname:"Whitfield", current: false, image:"https://vignette.wikia.nocookie.net/real-housewives/images/b/b8/Sheree-whitfield-full.png/revision/latest?cb=20151109172034")
kimz = Housewife.find_or_create_by(firstname:"Kim", lastname:"Zolciak-Biermann", current: false, image:"https://i.pinimg.com/originals/1c/3f/12/1c3f12febded638a3172a0fca49f434e.png")
lisawu = Housewife.find_or_create_by(firstname:"Lisa", lastname:"Wu", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2012/lisa-wu-hartwell-full.png")
deshawn = Housewife.find_or_create_by(firstname:"DeShawn", lastname:"Snow", current: false, image:"https://i0.wp.com/allthingsrh.com/wp-content/uploads/2013/10/deshawn-snow-full.png?fit=400%2C600")
kandi = Housewife.find_or_create_by(firstname:"Kandi", lastname:"Burruss", current: true, image:"http://thegospelguru.com/wp-content/uploads/2013/02/kandi-burruss-full-alt.png")
cynthia = Housewife.find_or_create_by(firstname:"Cynthia", lastname:"Bailey", current: true, image:"https://the-hollywood-gossip-res.cloudinary.com/iu/s--emF366yH--/c_scale,f_auto,h_1856,q_auto,w_696/v1422466233/cynthia-bailey-promo-pic")
phaedra = Housewife.find_or_create_by(firstname:"Phaedra", lastname:"Parks", current: false, image:"https://i.ibb.co/WB5wN8y/Phaedra.png")
porsha = Housewife.find_or_create_by(firstname:"Porsha", lastname:"Williams", current: true, image:"https://i.ibb.co/3Wq0Zsg/Porsha.png")
kenya = Housewife.find_or_create_by(firstname:"Kenya", lastname:"Moore", current: true, image:"https://bossip.files.wordpress.com/2015/09/kenya-moore-full.png?w=468&h=1712")
claudia = Housewife.find_or_create_by(firstname:"Claudia", lastname:"Jordan", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2014/claudia-jordan-full.png")
kimf = Housewife.find_or_create_by(firstname:"Kim", lastname:"Fields", current: false, image:"https://www.bravotv.com/sites/bravo/files/field_person_full_photo/2015/09/kim-fields-full.png")
eva = Housewife.find_or_create_by(firstname:"Eva", lastname:"Marcille", current: true, image:"https://i2.wp.com/www.celebrity-cutouts.com/wp-content/uploads/2019/07/eva-marcille-pink-dress-cardboard-cutout.png?resize=450%2C500&ssl=1")
shamari = Housewife.find_or_create_by(firstname:"Shamari", lastname:"DeVoe", current: false, image:"https://i.ibb.co/X4Pk9z4/Shamari.png")

# RHOA SEASONS
rhoa1 = Season.find_or_create_by(season: 1, city: "Atlanta")
rhoa2 = Season.find_or_create_by(season: 2, city: "Atlanta")
rhoa3 = Season.find_or_create_by(season: 3, city: "Atlanta")
rhoa4 = Season.find_or_create_by(season: 4, city: "Atlanta")
rhoa5 = Season.find_or_create_by(season: 5, city: "Atlanta")
rhoa6 = Season.find_or_create_by(season: 6, city: "Atlanta")
rhoa7 = Season.find_or_create_by(season: 7, city: "Atlanta")
rhoa8 = Season.find_or_create_by(season: 8, city: "Atlanta")
rhoa9 = Season.find_or_create_by(season: 9, city: "Atlanta")
rhoa10 = Season.find_or_create_by(season: 10, city: "Atlanta")
rhoa11 = Season.find_or_create_by(season: 11, city: "Atlanta")

# RHOA TAGLINES
# RHOA S1 TAGLINES
s1nene = Tagline.find_or_create_by(tagline: "I don’t keep up with the Joneses; I am the Joneses.", housewife_id: nene.id, season_id: rhoa1.id)
s1deshawn = Tagline.find_or_create_by(tagline: "I always knew I was destined for greatness.", housewife_id: deshawn.id, season_id: rhoa1.id)
s1kim = Tagline.find_or_create_by(tagline: "In Atlanta, money and class do give you power.", housewife_id: kimz.id, season_id: rhoa1.id)
s1lisawu = Tagline.find_or_create_by(tagline: "If it doesn’t make me money, I don’t do it.", housewife_id: lisawu.id, season_id: rhoa1.id)
s1sheree = Tagline.find_or_create_by(tagline: "People are intimidated by my success.", housewife_id: sheree.id, season_id: rhoa1.id)
# RHOA S2 TAGLINES
s2kandi = Tagline.find_or_create_by(tagline: "I'm an independent woman, doing it for myself.", housewife_id: kandi.id, season_id: rhoa2.id)
s2kim = Tagline.find_or_create_by(tagline: "In Atlanta, money and class do give you power.", housewife_id: kimz.id, season_id: rhoa2.id)
s2lisawu = Tagline.find_or_create_by(tagline: "If it doesn’t make me money, I don’t do it.", housewife_id: lisawu.id, season_id: rhoa2.id)
s2nene = Tagline.find_or_create_by(tagline: "I don’t keep up with the Joneses; I am the Joneses.", housewife_id: nene.id, season_id: rhoa2.id)
s2sheree = Tagline.find_or_create_by(tagline: "People are intimidated by my success.", housewife_id: sheree.id, season_id: rhoa2.id)
# RHOA S3 TAGLINES
s3cynthia = Tagline.find_or_create_by(tagline: "I know how to work it, and be seen.", housewife_id: cynthia.id, season_id: rhoa3.id)
s3kandi = Tagline.find_or_create_by(tagline: "I have fame and fortune, and I’ve earned it.", housewife_id: kandi.id, season_id: rhoa3.id)
s3kim = Tagline.find_or_create_by(tagline: "People call me a gold digger, but they just want what I have.", housewife_id: kimz.id, season_id: rhoa3.id)
s3nene = Tagline.find_or_create_by(tagline: "When I walk into the room, I own it.", housewife_id: nene.id, season_id: rhoa3.id)
s3phaedra = Tagline.find_or_create_by(tagline: "I’m the ultimate Southern belle, I get what I want.", housewife_id: phaedra.id, season_id: rhoa3.id)
s3sheree = Tagline.find_or_create_by(tagline: "I like things that are elegant and sophisticated, just like me.", housewife_id: sheree.id, season_id: rhoa3.id)
# RHOA S4 TAGLINES
s4cynthia = Tagline.find_or_create_by(tagline: "I know how to work it, and be seen.", housewife_id: cynthia.id, season_id: rhoa4.id)
s4kandi = Tagline.find_or_create_by(tagline: "I have fame and fortune, and I’ve earned it.", housewife_id: kandi.id, season_id: rhoa4.id)
s4kim = Tagline.find_or_create_by(tagline: "People call me a gold digger, but they just want what I have.", housewife_id: kimz.id, season_id: rhoa4.id)
s4nene = Tagline.find_or_create_by(tagline: "When I walk into the room, I own it.", housewife_id: nene.id, season_id: rhoa4.id)
s4phaedra = Tagline.find_or_create_by(tagline: "I’m the ultimate Southern belle, I get what I want.", housewife_id: phaedra.id, season_id: rhoa4.id)
s4sheree = Tagline.find_or_create_by(tagline: "I like things that are elegant and sophisticated, just like me.", housewife_id: sheree.id, season_id: rhoa4.id)
# RHOA S5 TAGLINES
s5cynthia = Tagline.find_or_create_by(tagline: "Beauty fades, class is forever.", housewife_id: cynthia.id, season_id: rhoa5.id)
s5kandi = Tagline.find_or_create_by(tagline: "I may be small, but my empire keeps on growing.", housewife_id: kandi.id, season_id: rhoa5.id)
s5kenya = Tagline.find_or_create_by(tagline: "I won Miss USA, not Miss Congeniality.", housewife_id: kenya.id, season_id: rhoa5.id)
s5kim = Tagline.find_or_create_by(tagline: "I asked, believed, and I received.", housewife_id: kimz.id, season_id: rhoa5.id)
s5nene = Tagline.find_or_create_by(tagline: "I have arrived, and the spotlight is on me, honey.", housewife_id: nene.id, season_id: rhoa5.id)
s5phaedra = Tagline.find_or_create_by(tagline: "I’m a Southern belle. Brains, booty, and all business.", housewife_id: phaedra.id, season_id: rhoa5.id)
s5porsha = Tagline.find_or_create_by(tagline: "People say I have a picture perfect life, and I do.", housewife_id: porsha.id, season_id: rhoa5.id)
# RHOA S6 TAGLINES
s6cynthia = Tagline.find_or_create_by(tagline: "My business is beauty, and I'm the boss.", housewife_id: cynthia.id, season_id: rhoa6.id)
s6kandi = Tagline.find_or_create_by(tagline: "Music may be my passion, but family is forever.", housewife_id: kandi.id, season_id: rhoa6.id)
s6kenya = Tagline.find_or_create_by(tagline: "People may think they have me figured out, but I am always the wild card.", housewife_id: kenya.id, season_id: rhoa6.id)
s6nene = Tagline.find_or_create_by(tagline: "Success is in my DNA. When one door closes, another one opens.", housewife_id: nene.id, season_id: rhoa6.id)
s6phaedra = Tagline.find_or_create_by(tagline: "A true southern belle knows her worth, and I am priceless.", housewife_id: phaedra.id, season_id: rhoa6.id)
s6porsha = Tagline.find_or_create_by(tagline: "I am still standing, and I am making my own rules.", housewife_id: porsha.id, season_id: rhoa6.id)
# RHOA S7 TAGLINES
s7claudia = Tagline.find_or_create_by(tagline: "Don't hate me because I'm beautiful. Hate me because I'm here to stay.", housewife_id: claudia.id, season_id: rhoa7.id)
s7cynthia = Tagline.find_or_create_by(tagline: "Life is about choices, and I choose Cynthia.", housewife_id: cynthia.id, season_id: rhoa7.id)
s7kandi = Tagline.find_or_create_by(tagline: "I'm not about the drama. Don't start none, won't be none.", housewife_id: kandi.id, season_id: rhoa7.id)
s7nene = Tagline.find_or_create_by(tagline: "Why be so nasty and so rude when I can be so fierce and so successful.", housewife_id: nene.id, season_id: rhoa7.id)
s7kenya = Tagline.find_or_create_by(tagline: "People get exhausted trying to figure me out, and I just let them.", housewife_id: kenya.id, season_id: rhoa7.id)
s7phaedra = Tagline.find_or_create_by(tagline: "When it comes to my family, I'm the judge and the jury.", housewife_id: phaedra.id, season_id: rhoa7.id)
# RHOA S8 TAGLINES
s8cynthia = Tagline.find_or_create_by(tagline: "Seasons may change, but Cynthia Bailey never goes out of style.", housewife_id: cynthia.id, season_id: rhoa8.id)
s8kandi = Tagline.find_or_create_by(tagline: "I'm a hitmaker, and this year I will reveal the best one.", housewife_id: kandi.id, season_id: rhoa8.id)
s8kenya = Tagline.find_or_create_by(tagline: "Don't come for me, unless I twirl for you.", housewife_id: kenya.id, season_id: rhoa8.id)
s8kimf = Tagline.find_or_create_by(tagline: "Faith, family and career -- those are the facts of my life.", housewife_id: kimf.id, season_id: rhoa8.id)
s8phaedra = Tagline.find_or_create_by(tagline: "Only God can judge me, and he seems quite impressed.", housewife_id: phaedra.id, season_id: rhoa8.id)
s8porsha = Tagline.find_or_create_by(tagline: "I'm about to give you life, so stay out of my way!", housewife_id: porsha.id, season_id: rhoa8.id)
# RHOA S9 TAGLINES
s9cynthia = Tagline.find_or_create_by(tagline: "Life is a runway, and Cynthia Bailey is ready to walk it alone.", housewife_id: cynthia.id, season_id: rhoa9.id)
s9kandi = Tagline.find_or_create_by(tagline: "Now that I’ve got my Ace, I’ve got a full house.", housewife_id: kandi.id, season_id: rhoa9.id)
s9kenya = Tagline.find_or_create_by(tagline: "I give the people what they want, and they always want Moore.", housewife_id: kenya.id, season_id: rhoa9.id)
s9phaedra = Tagline.find_or_create_by(tagline: "You can't always get what you want, but I can.", housewife_id: phaedra.id, season_id: rhoa9.id)
s9porsha = Tagline.find_or_create_by(tagline: "I'm too blessed to be stressed, and too sexy to be thirsty.", housewife_id: porsha.id, season_id: rhoa9.id)
s9sheree = Tagline.find_or_create_by(tagline: "Don't call it a comeback, call it a takeover!", housewife_id: sheree.id, season_id: rhoa9.id)
# RHOA S10 TAGLINES
s10cynthia = Tagline.find_or_create_by(tagline: "Age is just a number, but these cheekbones are timeless!", housewife_id: cynthia.id, season_id: rhoa10.id)
s10kandi = Tagline.find_or_create_by(tagline: "Don’t mess with the boss, 'cuz you might get fired.", housewife_id: kandi.id, season_id: rhoa10.id)
s10kenya = Tagline.find_or_create_by(tagline: "While some were saying 'I can't,' I was saying 'I do!'", housewife_id: kenya.id, season_id: rhoa10.id)
s10nene = Tagline.find_or_create_by(tagline: "10 years in the game, and I'm still the tastiest peach in Atlanta!", housewife_id: nene.id, season_id: rhoa10.id)
s10porsha = Tagline.find_or_create_by(tagline: "Friends come and go, but family is forever.", housewife_id: porsha.id, season_id: rhoa10.id)
s10sheree = Tagline.find_or_create_by(tagline: "Call me a bad server, because I always spill the tea!", housewife_id: sheree.id, season_id: rhoa10.id)
# RHOA S11 TAGLINES
s11nene = Tagline.find_or_create_by(tagline: "I am the glue for my wig and my family!", housewife_id: nene.id, season_id: rhoa11.id)
s11cynthia = Tagline.find_or_create_by(tagline: "I age like fine wine, and now, I am ready to chill.", housewife_id: cynthia.id, season_id: rhoa11.id)
s11kandi = Tagline.find_or_create_by(tagline: "I count my blessings—and my checks!", housewife_id: kandi.id, season_id: rhoa11.id)
s11eva = Tagline.find_or_create_by(tagline: "I live a model life. Now I’m ready to be a top wife.", housewife_id: eva.id, season_id: rhoa11.id)
s11shamari = Tagline.find_or_create_by(tagline: "I may be an open book, but that does not mean I am easily read.", housewife_id: shamari.id, season_id: rhoa11.id)
s11porsha = Tagline.find_or_create_by(tagline: "I took a lot of left turns but now, things are just right.", housewife_id: porsha.id, season_id: rhoa11.id)

# RHOBH HOUSEWIVES
taylor = Housewife.find_or_create_by(firstname:"Taylor", lastname:"Armstrong", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2012/taylor-armstrong-full_0.png")
camille = Housewife.find_or_create_by(firstname:"Camille", lastname:"Grammer", current: false, image:"https://i1.wp.com/allthingsrh.com/wp-content/uploads/2012/10/Camille-Grammer.png")
adrienne = Housewife.find_or_create_by(firstname:"Adrienne", lastname:"Maloof", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2012/adrienne-maloof-full_0.png")
kimr = Housewife.find_or_create_by(firstname:"Kim", lastname:"Richards", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2014/kim-richards-full.png")
kyle = Housewife.find_or_create_by(firstname:"Kyle", lastname:"Richards", current: true, image:"https://vignette.wikia.nocookie.net/real-housewives/images/7/74/Kyle-richards-full.png/revision/latest?cb=20151109202737")
lisa = Housewife.find_or_create_by(firstname:"Lisa", lastname:"Vanderpump", current: false, image:"https://www.glossmagazine.net/wp-content/uploads/2015/11/lisa-vanderpump.png")
brandig = Housewife.find_or_create_by(firstname:"Brandi", lastname:"Glanville", current: false, image:"https://vignette.wikia.nocookie.net/real-housewives/images/a/a9/Brandi-glanville-full.png/revision/latest?cb=20151112022631")
yolanda = Housewife.find_or_create_by(firstname:"Yolanda", lastname:"Hadid", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2014/yolanda-h-foster-full_0.png")
joyce = Housewife.find_or_create_by(firstname:"Joyce", lastname:"Giraud de Ohoven", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2013/joyce-giraud-de-ohoven-full.png")
carlton = Housewife.find_or_create_by(firstname:"Carlton", lastname:"Gebbia", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2013/carlton-gebbia-full.png")
rinna = Housewife.find_or_create_by(firstname:"Lisa", lastname:"Rinna", current: true, image:"http://allthingsrh.com/wp-content/uploads/2016/11/rhbh-fullbody-silo-lisa-rinna.png")
eileen = Housewife.find_or_create_by(firstname:"Eileen", lastname:"Davidson", current: false, image:"https://www.bravotv.com/sites/bravo/files/field_person_full_photo/2016/11/rhbh-fullbody-silo-eileen_-davidson.png")
erika = Housewife.find_or_create_by(firstname:"Erika", lastname:"Girardi", current: true, image:"https://vignette.wikia.nocookie.net/real-housewives/images/1/1d/Erika-girardi-full.png/revision/latest?cb=20151109205129")
kathryn = Housewife.find_or_create_by(firstname:"Kathryn", lastname:"Edwards", current: false, image:"https://i2.wp.com/allthingsrh.com/wp-content/uploads/2015/11/kathryn-edwards-full.png")
dorit = Housewife.find_or_create_by(firstname:"Dorit", lastname:"Kemsley", current: true, image:"https://i.pinimg.com/originals/8a/ae/54/8aae54b28047585f4f921b3fbcae8583.png")
teddi = Housewife.find_or_create_by(firstname:"Teddi", lastname:"Mellencamp Arroyave", current: true, image:"https://i.ibb.co/HrWmFNg/Teddi.png")
denise = Housewife.find_or_create_by(firstname:"Denise", lastname:"Richards", current: true, image:"https://i.ibb.co/0cbXGWn/Denise.png")

# RHOBH SEASONS
rhobh1 = Season.find_or_create_by(season: 1, city: "Beverly Hills")
rhobh2 = Season.find_or_create_by(season: 2, city: "Beverly Hills")
rhobh3 = Season.find_or_create_by(season: 3, city: "Beverly Hills")
rhobh4 = Season.find_or_create_by(season: 4, city: "Beverly Hills")
rhobh5 = Season.find_or_create_by(season: 5, city: "Beverly Hills")
rhobh6 = Season.find_or_create_by(season: 6, city: "Beverly Hills")
rhobh7 = Season.find_or_create_by(season: 7, city: "Beverly Hills")
rhobh8 = Season.find_or_create_by(season: 8, city: "Beverly Hills")
rhobh9 = Season.find_or_create_by(season: 9, city: "Beverly Hills")

# RHOBH TAGLINES
# RHOBH S1 TAGLINES
s1adrienne = Tagline.find_or_create_by(tagline: "Money is what I have, not who I am.", housewife_id: adrienne.id, season_id: rhobh1.id)
s1camille = Tagline.find_or_create_by(tagline: "It's time for me to come out of my husband's shadow and shine.", housewife_id: camille.id, season_id: rhobh1.id)
s1kimr = Tagline.find_or_create_by(tagline: "I was a child star, but now my most important role is being a mother.", housewife_id: kimr.id, season_id: rhobh1.id)
s1kyle = Tagline.find_or_create_by(tagline: "In a town full of phonies, I'm not afraid to be me.", housewife_id: kyle.id, season_id: rhobh1.id)
s1lisa = Tagline.find_or_create_by(tagline: "In Beverly Hills it's who you know, and I know everyone.", housewife_id: lisa.id, season_id: rhobh1.id)
s1taylor = Tagline.find_or_create_by(tagline: "It may look like I have it all, but I want more.", housewife_id: taylor.id, season_id: rhobh1.id)
# RHOBH S2 TAGLINES
s2adrienne = Tagline.find_or_create_by(tagline: "Having it all is easy, if you're willing to work for it.", housewife_id: adrienne.id, season_id: rhobh2.id)
s2camille = Tagline.find_or_create_by(tagline: "Diamonds aren't a girl's best friend- freedom is.", housewife_id: camille.id, season_id: rhobh2.id)
s2kimr = Tagline.find_or_create_by(tagline: "People try to figure me out, but I'm one of a kind.", housewife_id: kimr.id, season_id: rhobh2.id)
s2kyle = Tagline.find_or_create_by(tagline: "I'm not the richest girl in Beverly Hills, but I am the luckiest.", housewife_id: kyle.id, season_id: rhobh2.id)
s2lisa = Tagline.find_or_create_by(tagline: "Life in Beverly Hills is a game, and I make the rules.", housewife_id: lisa.id, season_id: rhobh2.id)
s2taylor = Tagline.find_or_create_by(tagline: "I finally found my voice, and I'm not afraid to use it.", housewife_id: taylor.id, season_id: rhobh2.id)
# RHOBH S3 TAGLINES
s3adrienne = Tagline.find_or_create_by(tagline: "Having it all is easy, if you're willing to work for it.", housewife_id: adrienne.id, season_id: rhobh3.id)
s3brandig = Tagline.find_or_create_by(tagline: "Having it all is easy, if you're willing to work for it.", housewife_id: brandig.id, season_id: rhobh3.id)
s3kimr = Tagline.find_or_create_by(tagline: "Having it all is easy, if you're willing to work for it.", housewife_id: kimr.id, season_id: rhobh3.id)
s3kyle = Tagline.find_or_create_by(tagline: "Having it all is easy, if you're willing to work for it.", housewife_id: kyle.id, season_id: rhobh3.id)
s3lisa = Tagline.find_or_create_by(tagline: "Having it all is easy, if you're willing to work for it.", housewife_id: lisa.id, season_id: rhobh3.id)
s3taylor = Tagline.find_or_create_by(tagline: "Having it all is easy, if you're willing to work for it.", housewife_id: taylor.id, season_id: rhobh3.id)
s3yolanda = Tagline.find_or_create_by(tagline: "Having it all is easy, if you're willing to work for it.", housewife_id: yolanda.id, season_id: rhobh3.id)
# RHOBH S4 TAGLINES
s4brandig = Tagline.find_or_create_by(tagline: "In Beverly Hills, the higher you climb the farther you fall.", housewife_id: brandig.id, season_id: rhobh4.id)
s4carlton = Tagline.find_or_create_by(tagline: "In my world, money doesn’t talk, it swears.", housewife_id: carlton.id, season_id: rhobh4.id)
s4joyce = Tagline.find_or_create_by(tagline: "You can never be too young, too thin, or too honest.", housewife_id: joyce.id, season_id: rhobh4.id)
s4kimr = Tagline.find_or_create_by(tagline: "Everybody loves a comeback story, especially starring me.", housewife_id: kimr.id, season_id: rhobh4.id)
s4kyle = Tagline.find_or_create_by(tagline: "I’m from this town. I know what’s real and I know what’s fake.", housewife_id: kyle.id, season_id: rhobh4.id)
s4lisa = Tagline.find_or_create_by(tagline: "Life is a sexy little dance, and I like to take the lead.", housewife_id: lisa.id, season_id: rhobh4.id)
s4yolanda = Tagline.find_or_create_by(tagline: "Don’t tell me you’re my friend, act like one.", housewife_id: yolanda.id, season_id: rhobh4.id)
# RHOBH S5 TAGLINES
s5brandig = Tagline.find_or_create_by(tagline: "I’d rather spend my life kicking ass than kissing it.", housewife_id: brandig.id, season_id: rhobh5.id)
s5eileen = Tagline.find_or_create_by(tagline: "I’m not a bitch, but I’ve played one on TV.", housewife_id: eileen.id, season_id: rhobh5.id)
s5kimr = Tagline.find_or_create_by(tagline: "I’ve been rich and I’ve been famous, but happiness beats them both.", housewife_id: kimr.id, season_id: rhobh5.id)
s5kyle = Tagline.find_or_create_by(tagline: "Planes and yachts are nice, but my happiness starts at home.", housewife_id: kyle.id, season_id: rhobh5.id)
s5rinna = Tagline.find_or_create_by(tagline: "You’ve heard a lot about me, but it’s only true when it comes from my lips.", housewife_id: rinna.id, season_id: rhobh5.id)
s5lisa = Tagline.find_or_create_by(tagline: "Throw me to the wolves and I shall return, leading the pack.", housewife_id: lisa.id, season_id: rhobh5.id)
s5yolanda = Tagline.find_or_create_by(tagline: "Character isn’t what you have, it’s who you are.", housewife_id: yolanda.id, season_id: rhobh5.id)
# RHOBH S6 TAGLINES
s6eileen = Tagline.find_or_create_by(tagline: "I may be an actress, but that doesn’t mean I’ll stick to your script.", housewife_id: eileen.id, season_id: rhobh6.id)
s6erika = Tagline.find_or_create_by(tagline: "I’m an enigma, wrapped in a riddle, and cash.", housewife_id: erika.id, season_id: rhobh6.id)
s6kathryn = Tagline.find_or_create_by(tagline: "Don't hate the game, just marry a player.", housewife_id: kathryn.id, season_id: rhobh6.id)
s6kyle = Tagline.find_or_create_by(tagline: "In Beverly Hills you can be anything, but it’s most important to be yourself.", housewife_id: kyle.id, season_id: rhobh6.id)
s6rinna = Tagline.find_or_create_by(tagline: "My lips were made for talkin' and that’s just what they’ll do.", housewife_id: rinna.id, season_id: rhobh6.id)
s6lisa = Tagline.find_or_create_by(tagline: "I’m passionate about dogs, just not crazy about bitches.", housewife_id: lisa.id, season_id: rhobh6.id)
s6yolanda = Tagline.find_or_create_by(tagline: "Fake friends believe rumors, real friends believe in you.", housewife_id: yolanda.id, season_id: rhobh6.id)
# RHOBH S7 TAGLINES
s7dorit = Tagline.find_or_create_by(tagline: "When you've traveled the world, you can speak in any accent you want.", housewife_id: dorit.id, season_id: rhobh7.id)
s7eileen = Tagline.find_or_create_by(tagline: "I speak no evil, but I see and hear everything.", housewife_id: eileen.id, season_id: rhobh7.id)
s7erika = Tagline.find_or_create_by(tagline: "I may be two people, but I'm not two-faced.", housewife_id: erika.id, season_id: rhobh7.id)
s7kyle = Tagline.find_or_create_by(tagline: "I'm an expert on luxury, and I can always spot a fake.", housewife_id: kyle.id, season_id: rhobh7.id)
s7rinna = Tagline.find_or_create_by(tagline: "My advice to you: Don't hustle the hustler.", housewife_id: rinna.id, season_id: rhobh7.id)
s7lisa = Tagline.find_or_create_by(tagline: "The crown is heavy, darlings. So just leave it where it belongs.", housewife_id: lisa.id, season_id: rhobh7.id)
# RHOBH S8 TAGLINES
s8kyle = Tagline.find_or_create_by(tagline: "In this town, fame and money come and go, but friends should not.", housewife_id: kyle.id, season_id: rhobh8.id)
s8erika = Tagline.find_or_create_by(tagline: "Some people call me cold, but that's not ice. It's diamonds.", housewife_id: erika.id, season_id: rhobh8.id)
s8dorit = Tagline.find_or_create_by(tagline: "I believe in an excess of everything… except moderation.", housewife_id: dorit.id, season_id: rhobh8.id)
s8teddi = Tagline.find_or_create_by(tagline: "Having the best isn't important to me, but being my best is.", housewife_id: teddi.id, season_id: rhobh8.id)
s8rinna = Tagline.find_or_create_by(tagline: "I don't have to buy it, ‘cause I already own it.", housewife_id: rinna.id, season_id: rhobh8.id)
s8lisa = Tagline.find_or_create_by(tagline: "The queen of diamonds always has an ace up her sleeve.", housewife_id: lisa.id, season_id: rhobh8.id)
# RHOBH S9 TAGLINES
s9rinna = Tagline.find_or_create_by(tagline: "In the game of life, it’s Rinna take all.", housewife_id: rinna.id, season_id: rhobh9.id)
s9erika = Tagline.find_or_create_by(tagline: "Most people talk about their fantasies. I’m living mine.", housewife_id: erika.id, season_id: rhobh9.id)
s9dorit = Tagline.find_or_create_by(tagline: "In business and in life, I wear many hats… and hairstyles.", housewife_id: dorit.id, season_id: rhobh9.id)
s9lisa = Tagline.find_or_create_by(tagline: "You can stab me in the back, but whilst you’re there, kiss my ass.", housewife_id: lisa.id, season_id: rhobh9.id)
s9teddi = Tagline.find_or_create_by(tagline: "I’m not afraid of hard work, but I’ll never do your dirty work.", housewife_id: teddi.id, season_id: rhobh9.id)
s9denise = Tagline.find_or_create_by(tagline: "My problem with the tabloids? My real life is so much juicier.", housewife_id: denise.id, season_id: rhobh9.id)
s9kyle = Tagline.find_or_create_by(tagline: "In Beverly Hills, the truth always has a way of rising to the top.", housewife_id: kyle.id, season_id: rhobh9.id)

# RHOD HOUSEWIVES
cary = Housewife.find_or_create_by(firstname:"Cary", lastname:"Deuber", current: false, image:"https://i0.wp.com/allthingsrh.com/wp-content/uploads/2012/10/cary-deuber-full.png?fit=318%2C1200")
tiffany = Housewife.find_or_create_by(firstname:"Tiffany", lastname:"Hendra", current: false, image:"https://www.bravotv.com/sites/bravo/files/field_person_full_photo/2016/02/tiffany-hendra-full.png")
stephanie = Housewife.find_or_create_by(firstname:"Stephanie", lastname:"Hollman", current: true, image:"http://allthingsrh.com/wp-content/uploads/2012/10/stephanie-hollman-full.png")
leeanne = Housewife.find_or_create_by(firstname:"LeeAnne", lastname:"Locken", current: true, image:"https://i0.wp.com/allthingsrh.com/wp-content/uploads/2012/10/leeann-locken-full.png?fit=363%2C1200")
brandir = Housewife.find_or_create_by(firstname:"Brandi", lastname:"Redmond", current: true, image:"http://allthingsrh.com/wp-content/uploads/2012/10/brandi-redmond-full-332x1024.png")
dandra = Housewife.find_or_create_by(firstname:"D'Andra", lastname:"Simmons", current: true, image:"http://allthingsrh.com/wp-content/uploads/2017/07/DAndraSimmons.png")
kameron = Housewife.find_or_create_by(firstname:"Kameron", lastname:"Westcott", current: true, image:"https://i0.wp.com/allthingsrh.com/wp-content/uploads/2017/07/KameronWescott.png?fit=455%2C910")
kary = Housewife.find_or_create_by(firstname:"Kary", lastname:"Brittingham", current: true, image:"https://i.ibb.co/Gx79v62/Kary.png")

# RHOD SEASONS
rhod1 = Season.find_or_create_by(season: 1, city: "Dallas")
rhod2 = Season.find_or_create_by(season: 2, city: "Dallas")
rhod3 = Season.find_or_create_by(season: 3, city: "Dallas")
rhod4 = Season.find_or_create_by(season: 4, city: "Dallas")

# RHOD TAGLINES
# RHOD S1 TAGLINES
s1brandir = Tagline.find_or_create_by(tagline: "I was a Cowboys cheerleader, but in Dallas I'm never on the sidelines.", housewife_id: brandir.id, season_id: rhod1.id)
s1cary = Tagline.find_or_create_by(tagline: "I'm not a trophy wife, I'm a lifetime achievement award.", housewife_id: cary.id, season_id: rhod1.id)
s1leeanne = Tagline.find_or_create_by(tagline: "I grew up a carny kid. Play games with me and you're gonna pay.", housewife_id: leeanne.id, season_id: rhod1.id)
s1stephanie = Tagline.find_or_create_by(tagline: "I'm the girl next door, if you live in a big old mansion.", housewife_id: stephanie.id, season_id: rhod1.id)
s1tiffany = Tagline.find_or_create_by(tagline: "I came home to Dallas to shine my light, not to fight.", housewife_id: tiffany.id, season_id: rhod1.id)
# RHOD S2 TAGLINES
s2brandir = Tagline.find_or_create_by(tagline: "I cheered for the Cowboys, so I never get played.", housewife_id: brandir.id, season_id: rhod2.id)
s2stephanie = Tagline.find_or_create_by(tagline: "I married into money, but family is my fortune.", housewife_id: stephanie.id, season_id: rhod2.id)
s2cary = Tagline.find_or_create_by(tagline: "Every girl has skeletons in their closet. Mine are next to my Birkin.", housewife_id: cary.id, season_id: rhod2.id)
s2dandra = Tagline.find_or_create_by(tagline: "I started from the Dallas dynasty, but I’ll finish with my own empire.", housewife_id: dandra.id, season_id: rhod2.id)
s2kameron = Tagline.find_or_create_by(tagline: "Dumb blondes get noticed. Smart blondes get everything.", housewife_id: kameron.id, season_id: rhod2.id)
s2leeanne = Tagline.find_or_create_by(tagline: "I’m a true Texan. No bull, but all horns.", housewife_id: leeanne.id, season_id: rhod2.id)
# RHOD S3 TAGLINES
s3brandir = Tagline.find_or_create_by(tagline: "This isn't my first rodeo, so I'm not taking your bull.", housewife_id: brandir.id, season_id: rhod3.id)
s3cary = Tagline.find_or_create_by(tagline: "When life gets messy, just build a bigger closet.", housewife_id: cary.id, season_id: rhod3.id)
s3dandra = Tagline.find_or_create_by(tagline: "Running a family business is a job for one tough mother.", housewife_id: dandra.id, season_id: rhod3.id)
s3kameron = Tagline.find_or_create_by(tagline: "I've got heels that are higher than your standards.", housewife_id: kameron.id, season_id: rhod3.id)
s3leeanne = Tagline.find_or_create_by(tagline: "You don't mess with Texas, and you don't mess with me.", housewife_id: leeanne.id, season_id: rhod3.id)
s3stephanie = Tagline.find_or_create_by(tagline: "Investing in drama is not in my budget.", housewife_id: stephanie.id, season_id: rhod3.id)
# RHOD S4 TAGLINES
s4leeanne = Tagline.find_or_create_by(tagline: "Dallas is a pageant that I always win.", housewife_id: leeanne.id, season_id: rhod4.id)
s4kameron = Tagline.find_or_create_by(tagline: "Just because I look like Barbie, doesn't mean you can play me.", housewife_id: kameron.id, season_id: rhod4.id)
s4kary = Tagline.find_or_create_by(tagline: "I'm bilingual, but I don't speak BS.", housewife_id: kary.id, season_id: rhod4.id)
s4brandir = Tagline.find_or_create_by(tagline: "When you mess with a ginger, expect some spice.", housewife_id: brandir.id, season_id: rhod4.id)
s4dandra = Tagline.find_or_create_by(tagline: "I'm minding my business, so start minding yours.", housewife_id: dandra.id, season_id: rhod4.id)
s4stephanie = Tagline.find_or_create_by(tagline: "I never carry a grudge, it won't match my shoes.", housewife_id: stephanie.id, season_id: rhod4.id)

# RHODC HOUSEWIVES
cat = Housewife.find_or_create_by(firstname:"Cat", lastname:"Ommanney", current: false, image:"https://vignette.wikia.nocookie.net/real-housewives/images/a/a1/Catherin_Full.png/revision/latest?cb=20100812210133")
lynda = Housewife.find_or_create_by(firstname:"Lynda", lastname:"Erikiletian", current: false, image:"https://www.bravotv.com/sites/bravo/files/styles/cast-carousel/public/legacy/images/person/body/2012/body-lynda-erkiletian.png?itok=HOTwJVB0")
mary = Housewife.find_or_create_by(firstname:"Mary", lastname:"Amons", current: false, image:"https://www.bravotv.com/sites/bravo/files/styles/cast-carousel/public/legacy/images/person/body/2012/body-mary-schmidt-amons.png?itok=Q4P6fLfK")
michaele = Housewife.find_or_create_by(firstname:"Michaele", lastname:"Salahi", current: false, image:"https://www.bravotv.com/sites/bravo/files/styles/cast-carousel/public/legacy/images/person/body/2012/body-michaele-salahi.png?itok=boOOV2yF")
stacie = Housewife.find_or_create_by(firstname:"Stacie", lastname:"Turner", current: false, image:"https://www.bravotv.com/sites/bravo/files/styles/cast-carousel/public/legacy/images/person/body/2012/body-stacie-scott-turner.png?itok=VJF8o-Va")

# RHODC SEASONS
rhodc1 = Season.find_or_create_by(season: 1, city: "Washington, D.C.")

# RHODC TAGLINES
# RHODC S1 TAGLINES
s1mary = Tagline.find_or_create_by(tagline: "I don't make money, I spend money.", housewife_id: mary.id, season_id: rhodc1.id)
s1lynda = Tagline.find_or_create_by(tagline: "I give people enough rope to hang themselves, and the smart people don't.", housewife_id: lynda.id, season_id: rhodc1.id)
s1cat = Tagline.find_or_create_by(tagline: "I'm here for a good time, not a long time.", housewife_id: cat.id, season_id: rhodc1.id)
s1michaele = Tagline.find_or_create_by(tagline: "People have a hard time saying no to me and that’s just been my blessing.", housewife_id: michaele.id, season_id: rhodc1.id)
s1stacie = Tagline.find_or_create_by(tagline: "DC is my town and I thrive in it.", housewife_id: stacie.id, season_id: rhodc1.id)

# RHOM HOUSEWIVES
lea = Housewife.find_or_create_by(firstname:"Lea", lastname:"Black", current: false, image:"https://vignette.wikia.nocookie.net/real-housewives/images/4/4f/Lea-black-full.png/revision/latest?cb=20151115210707")
adriana = Housewife.find_or_create_by(firstname:"Adriana", lastname:"de Moura", current: false, image:"https://i1.wp.com/allthingsrh.com/wp-content/uploads/2012/10/adriana-de-moura-full.png?resize=250%2C600")
marysol = Housewife.find_or_create_by(firstname:"Marysol", lastname:"Patton", current: false, image:"https://i2.wp.com/allthingsrh.com/wp-content/uploads/2012/10/Marysol-Patton.png?resize=400%2C600")
alexia = Housewife.find_or_create_by(firstname:"Alexia", lastname:"Echevarria", current: false, image:"https://i1.wp.com/allthingsrh.com/wp-content/uploads/2012/10/alexia-echevarria-full.png")
larsa = Housewife.find_or_create_by(firstname:"Larsa", lastname:"Pippen", current: false, image:"https://i1.wp.com/allthingsrh.com/wp-content/uploads/2013/10/larsa-pippen-full.png")
cristy = Housewife.find_or_create_by(firstname:"Cristy", lastname:"Rice", current: false, image:"https://i0.wp.com/allthingsrh.com/wp-content/uploads/2013/10/cristy-rice-full.png")
lisah = Housewife.find_or_create_by(firstname:"Lisa", lastname:"Hochstein", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2013/lisa-hochstein-full.png")
joanna = Housewife.find_or_create_by(firstname:"Joanna", lastname:"Krupa", current: false, image:"https://i.pinimg.com/originals/ce/24/7d/ce247d5ea10b77e8d697db940982ddbc.png")
ana = Housewife.find_or_create_by(firstname:"Ana", lastname:"Quinoces", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2012/ana-quincoces-full.png")
karent = Housewife.find_or_create_by(firstname:"Karent", lastname:"Sierra", current: false, image:"http://3.bp.blogspot.com/-2iTbYCUcK9c/UTqdDKrjSwI/AAAAAAAACxo/v4hOTEmk69g/s1600/RHoMIA2-karent-sierra-full.png")

# RHOM SEASONS
rhom1 = Season.find_or_create_by(season: 1, city: "Miami")
rhom2 = Season.find_or_create_by(season: 2, city: "Miami")
rhom3 = Season.find_or_create_by(season: 3, city: "Miami")

# RHOM TAGLINES
# RHOM S1 TAGLINES
s1adriana = Tagline.find_or_create_by(tagline: "I speak five languages, but I can get a man with no words.", housewife_id: adriana.id, season_id: rhom1.id)
s1alexia = Tagline.find_or_create_by(tagline: "Beauty is power, if you know how to use it.", housewife_id: alexia.id, season_id: rhom1.id)
s1cristy = Tagline.find_or_create_by(tagline: "In my world, attitude is everything, I'm keeping it real.", housewife_id: cristy.id, season_id: rhom1.id)
s1larsa = Tagline.find_or_create_by(tagline: "My husband's got moves, but I run the game.", housewife_id: larsa.id, season_id: rhom1.id)
s1lea = Tagline.find_or_create_by(tagline: "I care about a lot of things, what others think of me isn't one of them.", housewife_id: lea.id, season_id: rhom1.id)
s1marysol = Tagline.find_or_create_by(tagline: "I put others in the spotlight, but somehow it keeps finding me.", housewife_id: marysol.id, season_id: rhom1.id)
# RHOM S2 TAGLINES
s2adriana = Tagline.find_or_create_by(tagline: "I may speak five languages, but my true language is independence.", housewife_id: adriana.id, season_id: rhom2.id)
s2ana = Tagline.find_or_create_by(tagline: "Whether in the court room or the kitchen, I bring the heat.", housewife_id: ana.id, season_id: rhom2.id)
s2joanna = Tagline.find_or_create_by(tagline: "I'm a model, but not always a model citizen.", housewife_id: joanna.id, season_id: rhom2.id)
s2karent = Tagline.find_or_create_by(tagline: "If you don't like my smile, then don't look my way.", housewife_id: karent.id, season_id: rhom2.id)
s2lea = Tagline.find_or_create_by(tagline: "I can deal with a lot, but I can't deal with stupid.", housewife_id: lea.id, season_id: rhom2.id)
s2marysol = Tagline.find_or_create_by(tagline: "My job is about making fast decisions, but my personal life I leave up to destiny.", housewife_id: marysol.id, season_id: rhom2.id)
s2lisah = Tagline.find_or_create_by(tagline: "My husband's a top plastic surgeon in this town, and I am his best creation.", housewife_id: lisah.id, season_id: rhom2.id)
# RHOM S3 TAGLINES
s3adriana = Tagline.find_or_create_by(tagline: "Some people say I have secrets, but I say I am full of surprises.", housewife_id: adriana.id, season_id: rhom3.id)
s3alexia = Tagline.find_or_create_by(tagline: "This Cuban doll is back on the scene, and living the dream.", housewife_id: alexia.id, season_id: rhom3.id)
s3joanna = Tagline.find_or_create_by(tagline: "Don't hate me because I have it all, hate me because I'm beautiful.", housewife_id: joanna.id, season_id: rhom3.id)
s3lea = Tagline.find_or_create_by(tagline: "I live my life like everything matters because I think it does.", housewife_id: lea.id, season_id: rhom3.id)
s3lisah = Tagline.find_or_create_by(tagline: "Everyone loves to underestimate me, and I love to prove everyone wrong.", housewife_id: lisah.id, season_id: rhom3.id)

# RHONJ HOUSEWIVES
teresa = Housewife.find_or_create_by(firstname:"Teresa", lastname:"Guidice", current: true, image:"https://vignette.wikia.nocookie.net/real-housewives/images/6/6e/TeresaGiudice1.png/revision/latest?cb=20150917221841")
jacqueline = Housewife.find_or_create_by(firstname:"Jacqueline", lastname:"Laurita", current: false, image:"https://www.bravotv.com/sites/bravo/files/field_person_full_photo/2016/05/jacqueline-laurita-full_0.png")
caroline = Housewife.find_or_create_by(firstname:"Carolina", lastname:"Manzo", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2014/caroline-manzo-full.png")
dina = Housewife.find_or_create_by(firstname:"Dina", lastname:"Manzo", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2014/dina-manzo-full.png")
danielle = Housewife.find_or_create_by(firstname:"Danielle", lastname:"Staub", current: false, image:"https://vignette.wikia.nocookie.net/real-housewives/images/e/eb/Danielle-staub-full.png/revision/latest?cb=20151117235136")
melissa = Housewife.find_or_create_by(firstname:"Melissa", lastname:"Gorga", current: true, image:"https://speakerdata2.s3.amazonaws.com/photo/image/902651/melissa-gorga-full-1.png")
kathyw = Housewife.find_or_create_by(firstname:"Kathy", lastname:"Wakile", current: false, image:"https://i.ibb.co/3RHcYvF/Kathy.png")
teresaa = Housewife.find_or_create_by(firstname:"Teresa", lastname:"Aprea", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2014/teresa-aprea-full.png")
amber = Housewife.find_or_create_by(firstname:"Amber", lastname:"Marchese", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2014/amber-marchese-full.png")
nicole = Housewife.find_or_create_by(firstname:"Nicole", lastname:"Napolitano", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2014/nicole-mauriello-full.png")
dolores = Housewife.find_or_create_by(firstname:"Dolores", lastname:"Catania", current: true, image:"https://i1.wp.com/allthingsrh.com/wp-content/uploads/2012/10/dolores-catania-full.png")
siggy = Housewife.find_or_create_by(firstname:"Siggy", lastname:"Flicker", current: false, image:"https://imgix.bustle.com/2016/7/0/siggy-flicker-full-56ac75a3-976b-4bc2-b0d4-1d3e4f418446.png")
margaret = Housewife.find_or_create_by(firstname:"Margaret", lastname:"Josephs", current: true, image:"https://i.ibb.co/gyS580M/Marg.png")
jackie = Housewife.find_or_create_by(firstname:"Jackie", lastname:"Goldschneider", current: true, image:"https://i.ibb.co/ryyHgGJ/Jackie.png")
jennifer = Housewife.find_or_create_by(firstname:"Jennifer", lastname:"Aydin", current: true, image:"https://i.ibb.co/5xykbg3/Jennifer.png")

# RHONJ SEASONS
rhonj1 = Season.find_or_create_by(season: 1, city: "New Jersey")
rhonj2 = Season.find_or_create_by(season: 2, city: "New Jersey")
rhonj3 = Season.find_or_create_by(season: 3, city: "New Jersey")
rhonj4 = Season.find_or_create_by(season: 4, city: "New Jersey")
rhonj5 = Season.find_or_create_by(season: 5, city: "New Jersey")
rhonj6 = Season.find_or_create_by(season: 6, city: "New Jersey")
rhonj7 = Season.find_or_create_by(season: 7, city: "New Jersey")
rhonj8 = Season.find_or_create_by(season: 8, city: "New Jersey")
rhonj9 = Season.find_or_create_by(season: 9, city: "New Jersey")
rhonj10 = Season.find_or_create_by(season: 10, city: "New Jersey")

# RHONJ TAGLINES
# RHONJ S1 TAGLINES
s1caroline = Tagline.find_or_create_by(tagline: "If you're gonna mess with my family, you’re messing with me.", housewife_id: caroline.id, season_id: rhonj1.id)
s1danielle = Tagline.find_or_create_by(tagline: "You're either gonna love me or hate me. There is no in between with me.", housewife_id: danielle.id, season_id: rhonj1.id)
s1dina = Tagline.find_or_create_by(tagline: "If you think I'm a bitch, then bring it on.", housewife_id: dina.id, season_id: rhonj1.id)
s1jacqueline = Tagline.find_or_create_by(tagline: "Everyone likes to have nice things, but I'm not one to brag about it.", housewife_id: jacqueline.id, season_id: rhonj1.id)
s1teresa = Tagline.find_or_create_by(tagline: "People make fun of Jersey girls, but I think they're just jealous.", housewife_id: teresa.id, season_id: rhonj1.id)
# RHONJ S2 TAGLINES
s2caroline = Tagline.find_or_create_by(tagline: "If you're gonna mess with my family, you’re messing with me.", housewife_id: caroline.id, season_id: rhonj2.id)
s2danielle = Tagline.find_or_create_by(tagline: "You're either gonna love me or hate me. There is no in between with me.", housewife_id: danielle.id, season_id: rhonj2.id)
s2dina = Tagline.find_or_create_by(tagline: "If you think I'm a bitch, then bring it on.", housewife_id: dina.id, season_id: rhonj2.id)
s2jacqueline = Tagline.find_or_create_by(tagline: "Everyone likes to have nice things, but I'm not one to brag about it.", housewife_id: jacqueline.id, season_id: rhonj2.id)
s2teresa = Tagline.find_or_create_by(tagline: "People make fun of Jersey girls, but I think they're just jealous.", housewife_id: teresa.id, season_id: rhonj2.id)
# RHONJ S3 TAGLINES
s3caroline = Tagline.find_or_create_by(tagline: "Life is about change, sometimes you just have to roll with the punches.", housewife_id: caroline.id, season_id: rhonj3.id)
s3jacqueline = Tagline.find_or_create_by(tagline: "I can hold my own. I am my own person.", housewife_id: jacqueline.id, season_id: rhonj3.id)
s3kathy = Tagline.find_or_create_by(tagline: "People say that I'm sweet, but I'm tough, so don't cross me.", housewife_id: kathyw.id, season_id: rhonj3.id)
s3melissa = Tagline.find_or_create_by(tagline: "I live a life that most girls only dream of.", housewife_id: melissa.id, season_id: rhonj3.id)
s3teresa = Tagline.find_or_create_by(tagline: "I'm a Jersey girl, no one can knock me down.", housewife_id: teresa.id, season_id: rhonj3.id)
# RHONJ S4 TAGLINES
s4caroline = Tagline.find_or_create_by(tagline: "Life is short, I have no time for drama.", housewife_id: caroline.id, season_id: rhonj4.id)
s4jacqueline = Tagline.find_or_create_by(tagline: "I am a Vegas girl, I will call your bluff.", housewife_id: jacqueline.id, season_id: rhonj4.id)
s4kathy = Tagline.find_or_create_by(tagline: "We're old school, we believe in respect.", housewife_id: kathyw.id, season_id: rhonj4.id)
s4melissa = Tagline.find_or_create_by(tagline: "I never throw the first punch, but I’m always a knockout.", housewife_id: melissa.id, season_id: rhonj4.id)
s4teresa = Tagline.find_or_create_by(tagline: "When times get tough, you learn who your real friends are.", housewife_id: teresa.id, season_id: rhonj4.id)
# RHONJ S5 TAGLINES
s5caroline = Tagline.find_or_create_by(tagline: "Love me or hate me, I always speak the truth.", housewife_id: caroline.id, season_id: rhonj5.id)
s5jacqueline = Tagline.find_or_create_by(tagline: "I've faced my share of challenges, but I'm tougher than I look.", housewife_id: jacqueline.id, season_id: rhonj5.id)
s5kathy = Tagline.find_or_create_by(tagline: "If you can't take the heat, get out of my kitchen.", housewife_id: kathyw.id, season_id: rhonj5.id)
s5melissa = Tagline.find_or_create_by(tagline: "Sexy life, loyal wife, take a page from my book.", housewife_id: melissa.id, season_id: rhonj5.id)
s5teresa = Tagline.find_or_create_by(tagline: "Haters are gonna hate, but I just love, love, love.", housewife_id: teresa.id, season_id: rhonj5.id)
# RHONJ S6 TAGLINES
s6teresa = Tagline.find_or_create_by(tagline: "You never know how strong you are until it’s the only choice you have.", housewife_id: teresa.id, season_id: rhonj6.id)
s6melissa = Tagline.find_or_create_by(tagline: "I’ve learned to forgive and never regret.", housewife_id: melissa.id, season_id: rhonj6.id)
s6teresaa = Tagline.find_or_create_by(tagline: "You’re not seeing double, you’re seeing trouble!", housewife_id: teresaa.id, season_id: rhonj6.id)
s6nicole = Tagline.find_or_create_by(tagline: "You’re not seeing double, you’re seeing trouble!", housewife_id: nicole.id, season_id: rhonj6.id)
s6amber = Tagline.find_or_create_by(tagline: "I’m a survivor, no one is bringing me down.", housewife_id: amber.id, season_id: rhonj6.id)
s6dina = Tagline.find_or_create_by(tagline: "I’m back to bring the zen. Namaste, bitches!", housewife_id: dina.id, season_id: rhonj6.id)
# RHONJ S7 TAGLINES
s7jacqueline = Tagline.find_or_create_by(tagline: "Fool me once, shame on me. Fool me twice, you better run.", housewife_id: jacqueline.id, season_id: rhonj7.id)
s7melissa = Tagline.find_or_create_by(tagline: "I always act like a lady, but now I think like a boss.", housewife_id: melissa.id, season_id: rhonj7.id)
s7dolores = Tagline.find_or_create_by(tagline: "I was raised Jersey strong. Nothing in this life can shake me.", housewife_id: dolores.id, season_id: rhonj7.id)
s7siggy = Tagline.find_or_create_by(tagline: "Some people think I'm too much. They're absolutely right.", housewife_id: siggy.id, season_id: rhonj7.id)
s7teresa = Tagline.find_or_create_by(tagline: "I used to flip tables, now I'm turning them.", housewife_id: teresa.id, season_id: rhonj7.id)
# RHONJ S8 TAGLINES
s8dolores = Tagline.find_or_create_by(tagline: "Look up loyalty in the dictionary, and you'll find my face.", housewife_id: dolores.id, season_id: rhonj8.id)
s8melissa = Tagline.find_or_create_by(tagline: "The only life I envy is my own.", housewife_id: melissa.id, season_id: rhonj8.id)
s8margaret = Tagline.find_or_create_by(tagline: "I bring the power, the pigtails and the party.", housewife_id: margaret.id, season_id: rhonj8.id)
s8siggy = Tagline.find_or_create_by(tagline: "My motto is know your worth, leave the rest to your plastic surgeon.", housewife_id: siggy.id, season_id: rhonj8.id)
s8teresa = Tagline.find_or_create_by(tagline: "If you're not about the namaste, then get the hell out of my way.", housewife_id: teresa.id, season_id: rhonj8.id)
# RHONJ S9 TAGLINES
s9dolores = Tagline.find_or_create_by(tagline: "I may put up a tough front, but I'll never leave you behind.", housewife_id: dolores.id, season_id: rhonj9.id)
s9jackie = Tagline.find_or_create_by(tagline: "I have four kids, two degrees, and one kickass life.", housewife_id: jackie.id, season_id: rhonj9.id)
s9jennifer = Tagline.find_or_create_by(tagline: "I'm obsessed with family, traditions, and Chanel.", housewife_id: jennifer.id, season_id: rhonj9.id)
s9margaret = Tagline.find_or_create_by(tagline: "I can make you laugh or make you cry...your choice.", housewife_id: margaret.id, season_id: rhonj9.id)
s9melissa = Tagline.find_or_create_by(tagline: "Don't try to bully me, because I'm a boss.", housewife_id: melissa.id, season_id: rhonj9.id)
s9teresa = Tagline.find_or_create_by(tagline: "These days, I don't throw punches...I roll with them.", housewife_id: teresa.id, season_id: rhonj9.id)
# RHONJ S10 TAGLINES
s10dolores = Tagline.find_or_create_by(tagline: "Behind ever strong man is a stronger Jersey girl.", housewife_id: dolores.id, season_id: rhonj10.id)
s10jackie = Tagline.find_or_create_by(tagline: "Don’t let the minivan fool you. This mom won’t roll over for anyone.", housewife_id: jackie.id, season_id: rhonj10.id)
s10jennifer = Tagline.find_or_create_by(tagline: "As I always say, plastic makes perfect.", housewife_id: jennifer.id, season_id: rhonj10.id)
s10margaret = Tagline.find_or_create_by(tagline: "If you can’t take the truth, sue me.", housewife_id: margaret.id, season_id: rhonj10.id)
s10melissa = Tagline.find_or_create_by(tagline: "Mirror mirror on the wall, I don’t think I look 40 at all.", housewife_id: melissa.id, season_id: rhonj10.id)
s10teresa = Tagline.find_or_create_by(tagline: "If you rub me the wrong way, they’ll be no more namaste.", housewife_id: teresa.id, season_id: rhonj10.id)

# RHONY HOUSEWIVES
luann = Housewife.find_or_create_by(firstname:"Luann", lastname:"de Lesseps", current: true, image:"https://vignette.wikia.nocookie.net/real-housewives/images/7/78/Luann-de-lesseps-full-v2_2.png/revision/latest?cb=20151116004026")
bethenny = Housewife.find_or_create_by(firstname:"Bethenny", lastname:"Frankel", current: false, image:"https://i0.wp.com/allthingsrh.com/wp-content/uploads/2013/10/bethenny-frankel-full.png?fit=400%2C600")
alex = Housewife.find_or_create_by(firstname:"Alex", lastname:"McCord", current: false, image:"https://i1.wp.com/allthingsrh.com/wp-content/uploads/2013/10/alex-mccord-full.png")
ramona = Housewife.find_or_create_by(firstname:"Ramona", lastname:"Singer", current: true, image:"https://vignette.wikia.nocookie.net/real-housewives/images/6/63/Ramona-singer-full.png/revision/latest/scale-to-width-down/250?cb=20151205163005")
jill = Housewife.find_or_create_by(firstname:"Jill", lastname:"Zarin", current: false, image:"https://gillzaransucks.files.wordpress.com/2010/04/jill_03.png")
kellyb = Housewife.find_or_create_by(firstname:"Kelly", lastname:"Bensimon", current: false, image:"https://i0.wp.com/allthingsrh.com/wp-content/uploads/2012/09/former13.png")
sonja = Housewife.find_or_create_by(firstname:"Sonja", lastname:"Morgan", current: true, image:"https://vignette.wikia.nocookie.net/real-housewives/images/e/ee/Sonjamorgan1.png/revision/latest?cb=20150917221505")
cindy = Housewife.find_or_create_by(firstname:"Cindy", lastname:"Barshop", current: false, image:"https://vignette.wikia.nocookie.net/real-housewives/images/a/a8/Cindy-barshop-full.png/revision/latest?cb=20151121215511")
aviva = Housewife.find_or_create_by(firstname:"Aviva", lastname:"Drescher", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2014/aviva-drescher-full.png")
carole = Housewife.find_or_create_by(firstname:"Carole", lastname:"Radziwill", current: false, image:"https://vignette.wikia.nocookie.net/real-housewives/images/2/26/Carole-radziwill-full.png/revision/latest?cb=20151109190839")
heather = Housewife.find_or_create_by(firstname:"Heather", lastname:"Thompson", current: false, image:"https://vignette.wikia.nocookie.net/real-housewives/images/2/2a/Heather-thomson-full.png/revision/latest?cb=20151112183414")
kristen = Housewife.find_or_create_by(firstname:"Kristen", lastname:"Taekman", current: false, image:"http://3.bp.blogspot.com/-XHLisQy3KM4/VKLwG76qfWI/AAAAAAAAFHo/IsHDQSg7qtQ/s1600/RHoNYC6-kristen-taekman-full.png")
dorinda = Housewife.find_or_create_by(firstname:"Dorinda", lastname:"Medley", current: true, image:"http://2.bp.blogspot.com/-AkhRG-XZeOA/VPUvdGLyUAI/AAAAAAAAFp8/91dQEqi5NAo/s1600/dorinda-medley-full.png")
jules = Housewife.find_or_create_by(firstname:"Jules", lastname:"Wainstein", current: false, image:"https://www.bravotv.com/sites/bravo/files/field_person_full_photo/2016/02/julianne-wainstein-full.png")
tinsley = Housewife.find_or_create_by(firstname:"Tinsley", lastname:"Mortimer", current: true, image:"https://i.ibb.co/cLbPXcN/Tinsley.png")

# RHONY SEASONS
rhony1 = Season.find_or_create_by(season: 1, city: "New York")
rhony2 = Season.find_or_create_by(season: 2, city: "New York")
rhony3 = Season.find_or_create_by(season: 3, city: "New York")
rhony4 = Season.find_or_create_by(season: 4, city: "New York")
rhony5 = Season.find_or_create_by(season: 5, city: "New York")
rhony6 = Season.find_or_create_by(season: 6, city: "New York")
rhony7 = Season.find_or_create_by(season: 7, city: "New York")
rhony8 = Season.find_or_create_by(season: 8, city: "New York")
rhony9 = Season.find_or_create_by(season: 9, city: "New York")
rhony10 = Season.find_or_create_by(season: 10, city: "New York")
rhony11 = Season.find_or_create_by(season: 11, city: "New York")
rhony12 = Season.find_or_create_by(season: 12, city: "New York")

# RHONY TAGLINES
# RHONY S1 TAGLINES
s1alex = Tagline.find_or_create_by(tagline: "To a certain group of people in New York, status is everything.", housewife_id: alex.id, season_id: rhony1.id)
s1luann = Tagline.find_or_create_by(tagline: "I never feel guilty about being privileged.", housewife_id: luann.id, season_id: rhony1.id)
s1bethenny = Tagline.find_or_create_by(tagline: "New York City is my playground.", housewife_id: bethenny.id, season_id: rhony1.id)
s1jill = Tagline.find_or_create_by(tagline: "I run with a fabulous circle of people.", housewife_id: jill.id, season_id: rhony1.id)
s1ramona = Tagline.find_or_create_by(tagline: "I like making my own money, I find that an aphrodisiac.", housewife_id: ramona.id, season_id: rhony1.id)
# RHONY S2 TAGLINES
s2alex = Tagline.find_or_create_by(tagline: "To a certain group of people in New York, status is everything.", housewife_id: alex.id, season_id: rhony2.id)
s2luann = Tagline.find_or_create_by(tagline: "I never feel guilty about being privileged.", housewife_id: luann.id, season_id: rhony2.id)
s2bethenny = Tagline.find_or_create_by(tagline: "New York City is my playground.", housewife_id: bethenny.id, season_id: rhony2.id)
s2jill = Tagline.find_or_create_by(tagline: "I run with a fabulous circle of people.", housewife_id: jill.id, season_id: rhony2.id)
s2ramona = Tagline.find_or_create_by(tagline: "I like making my own money, I find that an aphrodisiac.", housewife_id: ramona.id, season_id: rhony2.id)
s2kellyb = Tagline.find_or_create_by(tagline: "I've created a great life, and I love living it.", housewife_id: kellyb.id, season_id: rhony2.id)
# RHONY S3 TAGLINES
s3alex = Tagline.find_or_create_by(tagline: "To a certain group of people in New York, status is everything.", housewife_id: alex.id, season_id: rhony3.id)
s3luann = Tagline.find_or_create_by(tagline: "I never feel guilty about being privileged.", housewife_id: luann.id, season_id: rhony3.id)
s3bethenny = Tagline.find_or_create_by(tagline: "New York City is my playground.", housewife_id: bethenny.id, season_id: rhony3.id)
s3jill = Tagline.find_or_create_by(tagline: "I run with a fabulous circle of people.", housewife_id: jill.id, season_id: rhony3.id)
s3ramona = Tagline.find_or_create_by(tagline: "I like making my own money, I find that an aphrodisiac.", housewife_id: ramona.id, season_id: rhony3.id)
s3kellyb = Tagline.find_or_create_by(tagline: "I've created a great life, and I love living it.", housewife_id: kellyb.id, season_id: rhony3.id)
s3sonja = Tagline.find_or_create_by(tagline: "I have a taste for luxury and luxury has a taste for me.", housewife_id: sonja.id, season_id: rhony3.id)
# RHONY S4 TAGLINES
s4ramona = Tagline.find_or_create_by(tagline: "If people can't handle the truth, it's really not my problem.", housewife_id: ramona.id, season_id: rhony4.id)
s4luann = Tagline.find_or_create_by(tagline: "I thought I had it good before, but I'm just getting started.", housewife_id: luann.id, season_id: rhony4.id)
s4jill = Tagline.find_or_create_by(tagline: "Good or bad, I know who I am and I own it.", housewife_id: jill.id, season_id: rhony4.id)
s4alex = Tagline.find_or_create_by(tagline: "I've always had opinions, but now people know it.", housewife_id: alex.id, season_id: rhony4.id)
s4kellyb = Tagline.find_or_create_by(tagline: "I'm living the American Dream, one mistake at a time.", housewife_id: kellyb.id, season_id: rhony4.id)
s4sonja = Tagline.find_or_create_by(tagline: "I have a taste for luxury and luxury has a taste for me.", housewife_id: sonja.id, season_id: rhony4.id)
s4cindy = Tagline.find_or_create_by(tagline: "I have everything I've ever wanted, and it's all on my own terms.", housewife_id: cindy.id, season_id: rhony4.id)
# RHONY S5 TAGLINES
s5sonja = Tagline.find_or_create_by(tagline: "A little Sonja will spice up any party.", housewife_id: sonja.id, season_id: rhony5.id)
s5luann = Tagline.find_or_create_by(tagline: "To some people, living elegantly just comes naturally.", housewife_id: luann.id, season_id: rhony5.id)
s5carole = Tagline.find_or_create_by(tagline: "I may be a princess, but I'm definitely not a drama queen.", housewife_id: carole.id, season_id: rhony5.id)
s5heather = Tagline.find_or_create_by(tagline: "My success is built on making women look and feel their best. Holla!", housewife_id: heather.id, season_id: rhony5.id)
s5aviva = Tagline.find_or_create_by(tagline: "Never underestimate a woman born and raised in New York City.", housewife_id: aviva.id, season_id: rhony5.id)
s5ramona = Tagline.find_or_create_by(tagline: "I'm not afraid to say what everyone else is thinking.", housewife_id: ramona.id, season_id: rhony5.id)
# RHONY S6 TAGLINES
s6carole = Tagline.find_or_create_by(tagline: "If you're going to talk about me behind my back, at least check out my great ass.", housewife_id: carole.id, season_id: rhony6.id)
s6aviva = Tagline.find_or_create_by(tagline: "When people tell me I'm fake, I know they're just pulling my leg.", housewife_id: aviva.id, season_id: rhony6.id)
s6heather = Tagline.find_or_create_by(tagline: "A true New Yorker never backs down, and I'm no exception. Holla!", housewife_id: heather.id, season_id: rhony6.id)
s6kristen = Tagline.find_or_create_by(tagline: "I may not be the sharpest tool in the shed, but I'm pretty!", housewife_id: kristen.id, season_id: rhony6.id)
s6ramona = Tagline.find_or_create_by(tagline: "Get the Pinot ready, because it's Turtle Time!", housewife_id: ramona.id, season_id: rhony6.id)
s6sonja = Tagline.find_or_create_by(tagline: "Sometimes Sonja has to go commando. What can I say?", housewife_id: sonja.id, season_id: rhony6.id)
# RHONY S7 TAGLINES
s7carole = Tagline.find_or_create_by(tagline: "All play and no work makes me a happy girl.", housewife_id: carole.id, season_id: rhony7.id)
s7sonja = Tagline.find_or_create_by(tagline: "My yacht may have sailed, but my ship is comin' in.", housewife_id: sonja.id, season_id: rhony7.id)
s7ramona = Tagline.find_or_create_by(tagline: "I know I'm a piece of work, but now, I'm a work in progress.", housewife_id: ramona.id, season_id: rhony7.id)
s7luann = Tagline.find_or_create_by(tagline: "One should know... Never count out the Countess.", housewife_id: luann.id, season_id: rhony7.id)
s7kristen = Tagline.find_or_create_by(tagline: "Pretty is smarter than you think.", housewife_id: kristen.id, season_id: rhony7.id)
s7dorinda = Tagline.find_or_create_by(tagline: "I give Uptown a whole new attitude.", housewife_id: dorinda.id, season_id: rhony7.id)
s7heather = Tagline.find_or_create_by(tagline: "I'm stronger than anything in my way. Holla!", housewife_id: heather.id, season_id: rhony7.id)
s7bethenny = Tagline.find_or_create_by(tagline: "I'm not a Housewife, but I am real.", housewife_id: bethenny.id, season_id: rhony7.id)
# RHONY S8 TAGLINES
s8bethenny = Tagline.find_or_create_by(tagline: "If you can't handle the truth, you can't handle me.", housewife_id: bethenny.id, season_id: rhony8.id)
s8carole = Tagline.find_or_create_by(tagline: "I plan for the future but live in the moment.", housewife_id: carole.id, season_id: rhony8.id)
s8dorinda = Tagline.find_or_create_by(tagline: "Diamonds aren't a girl's best friend; martinis are!", housewife_id: dorinda.id, season_id: rhony8.id)
s8sonja = Tagline.find_or_create_by(tagline: "If being Sonja is so wrong, why does it feel so right?", housewife_id: sonja.id, season_id: rhony8.id)
s8jules = Tagline.find_or_create_by(tagline: "A Jew and an Asian walk into a bar... Then they had me!", housewife_id: jules.id, season_id: rhony8.id)
s8luann = Tagline.find_or_create_by(tagline: "If you can't be cool, you can't be with the Countess.", housewife_id: luann.id, season_id: rhony8.id)
s8ramona = Tagline.find_or_create_by(tagline: "Like a fine wine, I just get better with time.", housewife_id: ramona.id, season_id: rhony8.id)
# RHONY S9 TAGLINES
s9dorinda = Tagline.find_or_create_by(tagline: "I tell it like it is, but I always make it nice.", housewife_id: dorinda.id, season_id: rhony9.id)
s9ramona = Tagline.find_or_create_by(tagline: "I'm an acquired taste. You don't like me? Acquire some taste!", housewife_id: ramona.id, season_id: rhony9.id)
s9sonja = Tagline.find_or_create_by(tagline: "There's nothing grey about my gardens.", housewife_id: sonja.id, season_id: rhony9.id)
s9carole = Tagline.find_or_create_by(tagline: "In the politics of friendship, I win the popular vote.", housewife_id: carole.id, season_id: rhony9.id)
s9luann = Tagline.find_or_create_by(tagline: "The only title I'd trade Countess for is wife.", housewife_id: luann.id, season_id: rhony9.id)
s9tinsley = Tagline.find_or_create_by(tagline: "A good set of lashes can fix anything, even a mugshot.", housewife_id: tinsley.id, season_id: rhony9.id)
s9bethenny = Tagline.find_or_create_by(tagline: "If you're going to take a shot at this B, you better not miss.", housewife_id: bethenny.id, season_id: rhony9.id)
# RHONY S10 TAGLINES
s10carole = Tagline.find_or_create_by(tagline: "In the marathon of life, loyalty is everything.", housewife_id: carole.id, season_id: rhony10.id)
s10dorinda = Tagline.find_or_create_by(tagline: "I have a big heart, but little patience.", housewife_id: dorinda.id, season_id: rhony10.id)
s10ramona = Tagline.find_or_create_by(tagline: "Age is an issue of mind over matter: If you don't mind, it doesn't matter!", housewife_id: ramona.id, season_id: rhony10.id)
s10tinsley = Tagline.find_or_create_by(tagline: "Come on, why cook when I can order room service?!", housewife_id: tinsley.id, season_id: rhony10.id)
s10sonja = Tagline.find_or_create_by(tagline: "I'm not just a last name. I'm a legacy.", housewife_id: sonja.id, season_id: rhony10.id)
s10bethenny = Tagline.find_or_create_by(tagline: "It's great to be successful. But it's even better to B Strong.", housewife_id: bethenny.id, season_id: rhony10.id)
s10luann = Tagline.find_or_create_by(tagline: "The most interesting people make the best headlines.", housewife_id: luann.id, season_id: rhony10.id)
# RHONY S11 TAGLINES
s11luann = Tagline.find_or_create_by(tagline: "I plead guilty... to being fabulous.", housewife_id: luann.id, season_id: rhony11.id)
s11ramona = Tagline.find_or_create_by(tagline: "The only thing I'll settle for is more.", housewife_id: ramona.id, season_id: rhony11.id)
s11sonja = Tagline.find_or_create_by(tagline: "People call me over the top, but lately I prefer being a bottom.", housewife_id: sonja.id, season_id: rhony11.id)
s11tinsley = Tagline.find_or_create_by(tagline: "Game, set, now, I need a match.", housewife_id: tinsley.id, season_id: rhony11.id)
s11bethenny = Tagline.find_or_create_by(tagline: "When life gives me limes, I make margaritas.", housewife_id: bethenny.id, season_id: rhony11.id)
s11dorinda = Tagline.find_or_create_by(tagline: "If you've got a problem with me, it's your problem!", housewife_id: dorinda.id, season_id: rhony11.id)

# RHOC HOUSEWIVES
kimberly = Housewife.find_or_create_by(firstname:"Kimberly", lastname:"Bryant", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2012/kimberly-bryant-full.png")
jo = Housewife.find_or_create_by(firstname:"Jo", lastname:"De La Rosa", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2012/jo-de-la-rosa-full.png")
vicki = Housewife.find_or_create_by(firstname:"Vicki", lastname:"Gunvalson", current: false, image:"http://allthingsrh.com/wp-content/uploads/2012/10/vicki-gunvalson-full.png")
jeana = Housewife.find_or_create_by(firstname:"Jeana", lastname:"Keough", current: false, image:"https://i0.wp.com/allthingsrh.com/wp-content/uploads/2013/10/jeana-keough-full.png?fit=400%2C600")
lauri = Housewife.find_or_create_by(firstname:"Lauri", lastname:"Peterson", current: false, image:"https://i1.wp.com/allthingsrh.com/wp-content/uploads/2013/10/lauri-waring-peterson-full.png?fit=400%2C600")
tammy = Housewife.find_or_create_by(firstname:"Tammy", lastname:"Knickerbocker", current: false, image: "https://i1.wp.com/allthingsrh.com/wp-content/uploads/2013/10/tammy-knickerbocker-full.png?resize=400%2C600")
quinn = Housewife.find_or_create_by(firstname:"Quinn", lastname:"Fry", current: false, image: "https://i1.wp.com/allthingsrh.com/wp-content/uploads/2012/09/quinn.png")
tamra = Housewife.find_or_create_by(firstname:"Tamra", lastname:"Judge", current: true, image: "https://vignette.wikia.nocookie.net/real-housewives/images/c/ce/Tamra-judge-full_0.png/revision/latest?cb=20151110220618")
lynne = Housewife.find_or_create_by(firstname:"Lynne", lastname:"Curtin", current: false, image: "https://i0.wp.com/allthingsrh.com/wp-content/uploads/2013/10/lynne-curtin-full.png")
gretchen = Housewife.find_or_create_by(firstname:"Gretchen", lastname:"Rossi", current: false, image: "https://vignette.wikia.nocookie.net/real-housewives/images/4/49/Gretchen-rossi-full.png/revision/latest?cb=20151110221715")
alexis = Housewife.find_or_create_by(firstname:"Alexis", lastname:"Bellino", current: false, image: "https://i.pinimg.com/originals/67/8b/29/678b2946229c1e78b1bb44483606815e.png")
peggyt = Housewife.find_or_create_by(firstname: "Peggy", lastname:"Tanous", current: false, image: "https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2012/peggy-tanous-full.png")
heatherd = Housewife.find_or_create_by(firstname: "Heather", lastname:"Dubrow", current: false, image: "https://vignette.wikia.nocookie.net/real-housewives/images/3/3d/Heather-dubrow-full.png/revision/latest?cb=20151110221823")
lydia = Housewife.find_or_create_by(firstname: "Lydia", lastname:"McLaughlin", current: false, image: "https://vignette.wikia.nocookie.net/real-housewives/images/4/4d/Lydia-stirling-mclaughlin-full.png/revision/latest?cb=20151110221728")
shannon = Housewife.find_or_create_by(firstname: "Shannon", lastname:"Beador", current: true, image: "https://i2.wp.com/allthingsrh.com/wp-content/uploads/2015/05/shannon-beador-full.png")
lizzie = Housewife.find_or_create_by(firstname: "Lizzi", lastname:"Rovsek", current: false, image: "https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2014/lizzie-rovsek-full.png")
mke = Housewife.find_or_create_by(firstname: "Meghan", lastname:"King Edmonds", current: false, image: "https://i.ibb.co/2F5kHSt/Meghan.png")
kellyd = Housewife.find_or_create_by(firstname: "Kelly", lastname:"Dodd", current: true, image: "https://i.ibb.co/LkRKcYw/Kelly.png")
peggys = Housewife.find_or_create_by(firstname: "Peggy", lastname:"Sulahian", current: false, image: "https://i.ibb.co/C9N8M5d/Peggy.png")
gina = Housewife.find_or_create_by(firstname: "Gina", lastname:"Kirschenheiter", current: true, image: "https://i.ibb.co/K2RgXnM/Gina.png")
emily = Housewife.find_or_create_by(firstname: "Emily", lastname:"Simpson", current: true, image: "https://i.ibb.co/wCNWz2Z/Emily.png")
braunwyn = Housewife.find_or_create_by(firstname: "Braunwyn", lastname:"Windham-Burke", current: true, image: "https://i.ibb.co/JCkncMc/Braunwyn.png")

# RHOC SEASONS
rhoc1 = Season.find_or_create_by(season: 1, city: "Orange County")
rhoc2 = Season.find_or_create_by(season: 2, city: "Orange County")
rhoc3 = Season.find_or_create_by(season: 3, city: "Orange County")
rhoc4 = Season.find_or_create_by(season: 4, city: "Orange County")
rhoc5 = Season.find_or_create_by(season: 5, city: "Orange County")
rhoc6 = Season.find_or_create_by(season: 6, city: "Orange County")
rhoc7 = Season.find_or_create_by(season: 7, city: "Orange County")
rhoc8 = Season.find_or_create_by(season: 8, city: "Orange County")
rhoc9 = Season.find_or_create_by(season: 9, city: "Orange County")
rhoc10 = Season.find_or_create_by(season: 10, city: "Orange County")
rhoc11 = Season.find_or_create_by(season: 11, city: "Orange County")
rhoc12 = Season.find_or_create_by(season: 12, city: "Orange County")
rhoc13 = Season.find_or_create_by(season: 13, city: "Orange County")
rhoc14 = Season.find_or_create_by(season: 14, city: "Orange County")

# RHOC TAGLINES
# RHOC S1 TAGLINES
s1jeana = Tagline.find_or_create_by(tagline: "It's just money, you can't take it with you.", housewife_id: jeana.id, season_id: rhoc1.id)
s1jo = Tagline.find_or_create_by(tagline: "He's pretty much keeping me.", housewife_id: jo.id, season_id: rhoc1.id)
s1kimberly = Tagline.find_or_create_by(tagline: "85 percent of the women around here have had breast implants.", housewife_id: kimberly.id, season_id: rhoc1.id)
s1lauri = Tagline.find_or_create_by(tagline: "Are the police involved?", housewife_id: lauri.id, season_id: rhoc1.id)
s1vicki = Tagline.find_or_create_by(tagline: "I don’t wanna get old.", housewife_id: vicki.id, season_id: rhoc1.id)
# RHOC S2 TAGLINES
s2jeana = Tagline.find_or_create_by(tagline: "I have always wanted things. I crave money.", housewife_id: jeana.id, season_id: rhoc2.id)
s2jo = Tagline.find_or_create_by(tagline: "I deserve only the best... I'm worth it!", housewife_id: jo.id, season_id: rhoc2.id)
s2lauri = Tagline.find_or_create_by(tagline: "I was poor, I was rich, I was poor again and you know what? Having money is easier.", housewife_id: lauri.id, season_id: rhoc2.id)
s2vicki = Tagline.find_or_create_by(tagline: "Here's to not being fake.", housewife_id: vicki.id, season_id: rhoc2.id)
s2tammy = Tagline.find_or_create_by(tagline: "I don't let my kids or my exes drive me crazy.", housewife_id: tammy.id, season_id: rhoc2.id)
# RHOC S3 TAGLINES
s3jeana = Tagline.find_or_create_by(tagline: "I love money and now I'm loving life.", housewife_id: jeana.id, season_id: rhoc3.id)
s3lauri = Tagline.find_or_create_by(tagline: "You know what, I'm living the O.C. lifestyle again. I feel like royalty.", housewife_id: lauri.id, season_id: rhoc3.id)
s3quinn = Tagline.find_or_create_by(tagline: "I love having a younger man in my life.", housewife_id: quinn.id, season_id: rhoc3.id)
s3tammy = Tagline.find_or_create_by(tagline: "No matter how much money you have, you can always rely on others.", housewife_id: tammy.id, season_id: rhoc3.id)
s3tamra = Tagline.find_or_create_by(tagline: "I'm the hottest housewife in Orange County.", housewife_id: tamra.id, season_id: rhoc3.id)
s3vicki = Tagline.find_or_create_by(tagline: "Everything's got to be huge, large, and grand.", housewife_id: vicki.id, season_id: rhoc3.id)
# RHOC S4 TAGLINES
s4gretchen = Tagline.find_or_create_by(tagline: "I love the bling, I love the jewelry, I love it all.", housewife_id: gretchen.id, season_id: rhoc4.id)
s4jeana = Tagline.find_or_create_by(tagline: "It doesn't matter what happens in life, I do it my way.", housewife_id: jeana.id, season_id: rhoc4.id)
s4lauri = Tagline.find_or_create_by(tagline: "I still get pampered, I still get treated like a princess. I deserve it.", housewife_id: lauri.id, season_id: rhoc4.id)
s4lynne = Tagline.find_or_create_by(tagline: "I'm just your typical Orange County housewife. I am obsessed with being young.", housewife_id: lynne.id, season_id: rhoc4.id)
s4tamra = Tagline.find_or_create_by(tagline: "I'm not the new girl anymore, so watch out.", housewife_id: tamra.id, season_id: rhoc4.id)
s4vicki = Tagline.find_or_create_by(tagline: "I want the power and the money, and I want them both.", housewife_id: vicki.id, season_id: rhoc4.id)
# RHOC S5 TAGLINES
s5alexis = Tagline.find_or_create_by(tagline: "Am I high maintenance? Of course I am, look at me.", housewife_id: alexis.id, season_id: rhoc5.id)
s5gretchen = Tagline.find_or_create_by(tagline: "I'm smart, I'm sexy, and I'm confident. Of course people are gonna talk about me.", housewife_id: gretchen.id, season_id: rhoc5.id)
s5jeana = Tagline.find_or_create_by(tagline: "Money is a girl’s best friend, and I love friends.", housewife_id: jeana.id, season_id: rhoc5.id)
s5lynne = Tagline.find_or_create_by(tagline: "It's not about how much money you have, it's about how good you look spending it.", housewife_id: lynne.id, season_id: rhoc5.id)
s5tamra = Tagline.find_or_create_by(tagline: "Housewives come younger, but they don't come hotter.", housewife_id: tamra.id, season_id: rhoc5.id)
s5vicki = Tagline.find_or_create_by(tagline: "I love my family, I love my work, I love my life.", housewife_id: vicki.id, season_id: rhoc5.id)
# RHOC S6 TAGLINES
s6alexis = Tagline.find_or_create_by(tagline: "God is my savior, my husband is my king, and my body? It's sinful.", housewife_id: alexis.id, season_id: rhoc6.id)
s6gretchen = Tagline.find_or_create_by(tagline: "Happiness means never having to apologize for being me.", housewife_id: gretchen.id, season_id: rhoc6.id)
s6peggyt = Tagline.find_or_create_by(tagline: "Soccer moms drive mini vans, but this girl drives a Bentley.", housewife_id: peggyt.id, season_id: rhoc6.id)
s6tamra = Tagline.find_or_create_by(tagline: "I'm done being a trophy wife, freedom only makes me hotter.", housewife_id: tamra.id, season_id: rhoc6.id)
s6vicki = Tagline.find_or_create_by(tagline: "I make my own money, and I make my own rules.", housewife_id: vicki.id, season_id: rhoc6.id)
# RHOC S7 TAGLINES
s7alexis = Tagline.find_or_create_by(tagline: "I thank God every day for my life, and you would, too.", housewife_id: alexis.id, season_id: rhoc7.id)
s7gretchen = Tagline.find_or_create_by(tagline: "Don't call me a princess, call me the boss.", housewife_id: gretchen.id, season_id: rhoc7.id)
s7heatherd = Tagline.find_or_create_by(tagline: "I may be married to a plastic surgeon, but I'm 98 percent real.", housewife_id: heatherd.id, season_id: rhoc7.id)
s7tamra = Tagline.find_or_create_by(tagline: "I call the shots in my life now, and I have good aim.", housewife_id: tamra.id, season_id: rhoc7.id)
s7vicki = Tagline.find_or_create_by(tagline: "My tank is full and I'm driving into my future.", housewife_id: vicki.id, season_id: rhoc7.id)
# RHOC S8 TAGLINES
s8alexis = Tagline.find_or_create_by(tagline: "I don’t need to prove anything. I know who I am and God does too.", housewife_id: alexis.id, season_id: rhoc8.id)
s8gretchen = Tagline.find_or_create_by(tagline: "When the going gets tough, I just get stronger and stronger.", housewife_id: gretchen.id, season_id: rhoc8.id)
s8heatherd = Tagline.find_or_create_by(tagline: "Whoever said blondes have more fun, hasn't met me.", housewife_id: heatherd.id, season_id: rhoc8.id)
s8lydia = Tagline.find_or_create_by(tagline: "You only live once, but if you work it right, once is enough.", housewife_id: lydia.id, season_id: rhoc8.id)
s8tamra = Tagline.find_or_create_by(tagline: "The best thing about starting over is never looking back.", housewife_id: tamra.id, season_id: rhoc8.id)
s8vicki = Tagline.find_or_create_by(tagline: "I’m my own boss and it’s time for a raise.", housewife_id: vicki.id, season_id: rhoc8.id)
# RHOC S9 TAGLINES
s9heatherd = Tagline.find_or_create_by(tagline: "You may think I have it all, but I'm just getting started.", housewife_id: heatherd.id, season_id: rhoc9.id)
s9lizzie = Tagline.find_or_create_by(tagline: "Standing out is much more fun than fitting in.", housewife_id: lizzie.id, season_id: rhoc9.id)
s9shannon = Tagline.find_or_create_by(tagline: "The O.C. is full of secrets, but I have nothing to hide.", housewife_id: shannon.id, season_id: rhoc9.id)
s9tamra = Tagline.find_or_create_by(tagline: "I'm not getting older, I'm just getting bolder.", housewife_id: tamra.id, season_id: rhoc9.id)
s9vicki = Tagline.find_or_create_by(tagline: "I make my own rules, so don't expect me to follow yours.", housewife_id: vicki.id, season_id: rhoc9.id)
# RHOC S10 TAGLINES
s10heatherd = Tagline.find_or_create_by(tagline: "No one's life is perfect, but mine is pretty close.", housewife_id: heatherd.id, season_id: rhoc10.id)
s10mke = Tagline.find_or_create_by(tagline: "Now that I'm in the O.C., it's a whole new ball game.", housewife_id: mke.id, season_id: rhoc10.id)
s10shannon = Tagline.find_or_create_by(tagline: "When life gives you lemons, put nine in a bowl!", housewife_id: shannon.id, season_id: rhoc10.id)
s10tamra = Tagline.find_or_create_by(tagline: "Boldness comes at a cost, and I'm willing to pay.", housewife_id: tamra.id, season_id: rhoc10.id)
s10vicki = Tagline.find_or_create_by(tagline: "I am the OG of the O.C.; everyone else is just a copy.", housewife_id: vicki.id, season_id: rhoc10.id)
# RHOC S11 TAGLINES
s11heatherd = Tagline.find_or_create_by(tagline: "If at first you don't succeed, try it my way.", housewife_id: heatherd.id, season_id: rhoc11.id)
s11kellyd = Tagline.find_or_create_by(tagline: "I don't throw parties, I am the party.", housewife_id: kellyd.id, season_id: rhoc11.id)
s11mke = Tagline.find_or_create_by(tagline: "In the game of life, I choose my team wisely.", housewife_id: mke.id, season_id: rhoc11.id)
s11shannon = Tagline.find_or_create_by(tagline: "Karma's a bitch, so I don't have to be one.", housewife_id: shannon.id, season_id: rhoc11.id)
s11tamra = Tagline.find_or_create_by(tagline: "My faith is strong, and my ass isn't bad either.", housewife_id: tamra.id, season_id: rhoc11.id)
s11vicki = Tagline.find_or_create_by(tagline: "Before you judge me, you better be perfect.", housewife_id: vicki.id, season_id: rhoc11.id)
# RHOC S12 TAGLINES
s12kellyd = Tagline.find_or_create_by(tagline: "If I want your opinion, I'll give it to you.", housewife_id: kellyd.id, season_id: rhoc12.id)
s12lydia = Tagline.find_or_create_by(tagline: "If you can't take my sparkle, then stay off my rainbow.", housewife_id: lydia.id, season_id: rhoc12.id)
s12mke = Tagline.find_or_create_by(tagline: "I can handle a baby, and women who act like one.", housewife_id: mke.id, season_id: rhoc12.id)
s12peggys = Tagline.find_or_create_by(tagline: "I'm living the American dream, one sports car at a time.", housewife_id: peggys.id, season_id: rhoc12.id)
s12shannon = Tagline.find_or_create_by(tagline: "The truth is organic, but lies are just artificial.", housewife_id: shannon.id, season_id: rhoc12.id)
s12tamra = Tagline.find_or_create_by(tagline: "I'm pint sized, baptized, and highly prized.", housewife_id: tamra.id, season_id: rhoc12.id)
s12vicki = Tagline.find_or_create_by(tagline: "I go big or go home, and I am not going home.", housewife_id: vicki.id, season_id: rhoc12.id)
# RHOC S13 TAGLINES
s13emily = Tagline.find_or_create_by(tagline: "When you come from humble beginnings, you count your blessings...one diamond at a time.", housewife_id: emily.id, season_id: rhoc13.id)
s13gina = Tagline.find_or_create_by(tagline: "I speak the truth, even if it sounds funny when I say it.", housewife_id: gina.id, season_id: rhoc13.id)
s13kellyd = Tagline.find_or_create_by(tagline: "Call animal control, 'cuz there's a cougar on the loose in the OC.", housewife_id: kellyd.id, season_id: rhoc13.id)
s13shannon = Tagline.find_or_create_by(tagline: "Some people say I'm too much to handle. I say I'm just getting started.", housewife_id: shannon.id, season_id: rhoc13.id)
s13tamra = Tagline.find_or_create_by(tagline: "I'm still the hottest housewife in Orange County and, the toughest, too.", housewife_id: tamra.id, season_id: rhoc13.id)
s13vicki = Tagline.find_or_create_by(tagline: "The fun bus is leaving and, this time, I'm in the driver's seat.", housewife_id: vicki.id, season_id: rhoc13.id)
# RHOC S14 TAGLINES
s14shannon = Tagline.find_or_create_by(tagline: "The tables have turned… and this time, I’m dancing on them!", housewife_id: shannon.id, season_id: rhoc14.id)
s14tamra = Tagline.find_or_create_by(tagline: "These days faith, family and fitness are the only ‘F’s’ I give.", housewife_id: tamra.id, season_id: rhoc14.id)
s14gina = Tagline.find_or_create_by(tagline: "I’ve made mistakes in Orange County but I’ll fix them in a New York minute.", housewife_id: gina.id, season_id: rhoc14.id)
s14emily = Tagline.find_or_create_by(tagline: "In a town full of blondes, I’m legally brunette.", housewife_id: emily.id, season_id: rhoc14.id)
s14braunwyn = Tagline.find_or_create_by(tagline: "I manage to wrangle a family of nine and still look like a ten.", housewife_id: braunwyn.id, season_id: rhoc14.id)
s14kellyd = Tagline.find_or_create_by(tagline: "If you don’t want me to cross the line, don’t draw one.", housewife_id: kellyd.id, season_id: rhoc14.id)

# RHOP HOUSEWIVES
gizelle = Housewife.find_or_create_by(firstname:"Gizelle", lastname:"Bryant", current: true, image:"https://vignette.wikia.nocookie.net/real-housewives/images/a/ae/Gizelle-bryant-full.png/revision/latest?cb=20151112004826")
ashley = Housewife.find_or_create_by(firstname:"Ashley", lastname:"Darby", current: true, image:"https://vignette.wikia.nocookie.net/real-housewives/images/d/d2/Ashley-boalch-darby-full.png/revision/latest?cb=20151112002904")
robyn = Housewife.find_or_create_by(firstname:"Robyn", lastname:"Dixon", current: true, image:"https://vignette.wikia.nocookie.net/real-housewives/images/8/83/Robyn-dixon-full.png/revision/latest?cb=20151112004659")
karen = Housewife.find_or_create_by(firstname:"Karen", lastname:"Huger", current: true, image:"https://i.pinimg.com/originals/02/5a/d5/025ad5656bb1e756109471ceafeae00d.png")
charrisse = Housewife.find_or_create_by(firstname:"Charrisse", lastname:"Jackson-Jordan", current: false, image:"https://vignette.wikia.nocookie.net/real-housewives/images/b/b0/Charrisse-jackson-jordan-full.png/revision/latest?cb=20151112004204")
katie = Housewife.find_or_create_by(firstname:"Katie", lastname:"Rost", current: false, image:"https://static.wixstatic.com/media/ea81b3_95c330a5edfd477084a2557bfbbd641f~mv2.png/v1/fit/w_390%2Ch_1000%2Cal_c%2Cq_80/file.png")
monique = Housewife.find_or_create_by(firstname:"Monique", lastname:"Samuels", current: true, image:"https://i.ibb.co/kHSS4P5/Monique.png")
candiace = Housewife.find_or_create_by(firstname:"Candiace", lastname:"Dillard", current: true, image:"https://i.ibb.co/DwndTCH/Candiace.png")

# RHOP SEASONS
rhop1 = Season.find_or_create_by(season: 1, city: "Potomac")
rhop2 = Season.find_or_create_by(season: 2, city: "Potomac")
rhop3 = Season.find_or_create_by(season: 3, city: "Potomac")
rhop4 = Season.find_or_create_by(season: 4, city: "Potomac")

# RHOP TAGLINES
# RHOP S1 TAGLINES
s1gizelle = Tagline.find_or_create_by(tagline: "The word on the street is, that I'm the word on the street.", housewife_id: gizelle.id, season_id: rhop1.id)
s1karen = Tagline.find_or_create_by(tagline: "In Potomac, it's not about who you know, it's who you are. And I'm everything.", housewife_id: karen.id, season_id: rhop1.id)
s1katie = Tagline.find_or_create_by(tagline: "I'm a ball and gala girl. It's my legacy and my calling.", housewife_id: katie.id, season_id: rhop1.id)
s1robyn = Tagline.find_or_create_by(tagline: "I don't have a cookie cutter life and I'm not apologizing for it.", housewife_id: robyn.id, season_id: rhop1.id)
s1charrisse = Tagline.find_or_create_by(tagline: "If I don't know who you are, then you're not worth knowing.", housewife_id: charrisse.id, season_id: rhop1.id)
s1ashley = Tagline.find_or_create_by(tagline: "Throw this spring chicken into the cougar's den and let the games begin.", housewife_id: ashley.id, season_id: rhop1.id)
# RHOP S2 TAGLINES
s2gizelle = Tagline.find_or_create_by(tagline: "Word on the street is, I'm still the word on the street.", housewife_id: gizelle.id, season_id: rhop2.id)
s2karen = Tagline.find_or_create_by(tagline: "Potomac put me on a pedestal, and the view is spectacular.", housewife_id: karen.id, season_id: rhop2.id)
s2monique = Tagline.find_or_create_by(tagline: "I maybe rough around the edges, but baby, so are diamonds.", housewife_id: monique.id, season_id: rhop2.id)
s2robyn = Tagline.find_or_create_by(tagline: "Don't let the green eyes fool you, I'm as real as they come.", housewife_id: robyn.id, season_id: rhop2.id)
s2charrisse = Tagline.find_or_create_by(tagline: "Why cry over spilled milk, when you can laugh over champagne.", housewife_id: charrisse.id, season_id: rhop2.id)
s2ashley = Tagline.find_or_create_by(tagline: "I've played by Potomac rules, now it's time to play by my own.", housewife_id: ashley.id, season_id: rhop2.id)
# RHOP S3 TAGLINES
s3gizelle = Tagline.find_or_create_by(tagline: "If you can't handle me being the word on the street, then stop listening.", housewife_id: gizelle.id, season_id: rhop3.id)
s3karen = Tagline.find_or_create_by(tagline: "Baby don't believe what you hear, the Grand Dame still holds center court.", housewife_id: karen.id, season_id: rhop3.id)
s3monique = Tagline.find_or_create_by(tagline: "You'll never put me in a box, because I'm the whole darn package.", housewife_id: monique.id, season_id: rhop3.id)
s3robyn = Tagline.find_or_create_by(tagline: "Life has its ups and downs, but my game is on the rebound.", housewife_id: robyn.id, season_id: rhop3.id)
s3ashley = Tagline.find_or_create_by(tagline: "You may say I cause trouble, but I say I keep things interesting.", housewife_id: ashley.id, season_id: rhop3.id)
s3candiace = Tagline.find_or_create_by(tagline: "Life is a pageant, and I'm in it to win it.", housewife_id: candiace.id, season_id: rhop3.id)
# RHOP S4 TAGLINES
s4gizelle = Tagline.find_or_create_by(tagline: "I'm the baddest thing walkin' and the smartest one talkin'.", housewife_id: gizelle.id, season_id: rhop4.id)
s4karen = Tagline.find_or_create_by(tagline: "You can try to tear me down, but the Grande Dame never crumbles.", housewife_id: karen.id, season_id: rhop4.id)
s4monique = Tagline.find_or_create_by(tagline: "I've traded in my umbrella. It's all gold at the end of this rainbow.", housewife_id: monique.id, season_id: rhop4.id)
s4robyn = Tagline.find_or_create_by(tagline: "The shorter my hair, the shorter my patience.", housewife_id: robyn.id, season_id: rhop4.id)
s4ashley = Tagline.find_or_create_by(tagline: "Karma is a bitch. But luckily, I'm on her good side.", housewife_id: ashley.id, season_id: rhop4.id)
s4candiace = Tagline.find_or_create_by(tagline: "Now that I'm marrying my prince, this sleeping beauty is woke.", housewife_id: candiace.id, season_id: rhop4.id)

# FAKE USERS & RATINGS
User.destroy_all
Rating.destroy_all
peyton = User.find_or_create_by(username: "peyton", password: "123", image: "https://avatars2.githubusercontent.com/u/51932681?s=460&v=4", favcity: "New York", favhousewife: "Nene")
louis = User.find_or_create_by(username: "louis", password: "123", image: "https://avatars2.githubusercontent.com/u/51932681?s=460&v=4", favcity: "New York", favhousewife: "Nene")
rating1 = Rating.find_or_create_by(rating: 3, user_id: peyton.id, housewife_id: nene.id)
rating2 = Rating.find_or_create_by(rating: 5, user_id: louis.id, housewife_id: nene.id)


